### ISSUE TITLE
Cannot enable "direct references only" mode

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1112]
We use nuget package Microsoft.CrmSdk.CoreAssemblies version 6.1.1 and cannot update to newer version. Unfortunately that very package has a bug - it specifies dependency on Microsoft.IdentityModel for .NET 4.0 and 4.5, while actually it is only needed for 3.5.
As we target .NET 4.5 we are not supposed to pick up dependency on Microsoft.IdentityModel, but because of that package bug we do get it. 

I'm looking to work around that issue, by telling Paket to only take direct reference on Microsoft.CrmSdk.CoreAssemblies. I do it like that:

group Crm
	framework: net45
	references: strict
	source https://www.nuget.org/api/v2/
	nuget Microsoft.CrmSdk.CoreAssemblies 6.1.1

After "update -r" lock file still gives me
    Microsoft.CrmSdk.CoreAssemblies (6.1.1)
      Microsoft.IdentityModel (>= 6.1.7600.16394) - framework: >= net40

How to force it NOT to bring in its dependency?

**Comment by forki** [comment]
just tried to reproduce. For me it downloads Microsoft.IdentityModel and puts it in the lockfile (this is expected) but doesn't put it as a reference into the csproj file (also expected since you use strict mode). So Paket seems to do what you want. If you don't reference Microsoft.IdentityModel from the references file you don't get taht package in the project file.

 That said, there is still a .NET framework reference in Microsoft.CrmSdk.CoreAssemblies:

    <Choose>
      <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.5'">
        <ItemGroup>
          <Reference Include="Microsoft.Crm.Sdk.Proxy">
            <HintPath>..\..\packages\crm\Microsoft.CrmSdk.CoreAssemblies\lib\net45\Microsoft.Crm.Sdk.Proxy.dll</HintPath>
            <Private>True</Private>
            <Paket>True</Paket>
          </Reference>
          <Reference Include="Microsoft.Xrm.Sdk">
            <HintPath>..\..\packages\crm\Microsoft.CrmSdk.CoreAssemblies\lib\net45\Microsoft.Xrm.Sdk.dll</HintPath>
            <Private>True</Private>
            <Paket>True</Paket>
          </Reference>
          <Reference Include="Microsoft.IdentityModel">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.Core">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.DirectoryServices">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.DirectoryServices.AccountManagement">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.IdentityModel">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.Runtime.Serialization">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.ServiceModel">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.ServiceModel.Web">
            <Paket>True</Paket>
          </Reference>
          <Reference Include="System.Web">
            <Paket>True</Paket>
          </Reference>
        </ItemGroup>
      </When>
    </Choose>

**Comment by konste** [comment]
Include="Microsoft.IdentityModel" in .csproj IS the problem. It is indirect reference which I tried to avoid by using references: STRICT.

**Comment by forki** [comment]
Yes but as the docs state: only direct packages are referenced. And we do
that. It's part of the direct package.

As a temporarily fix: You should remove the reference manually and set all
other paket nodes to true. This should prevent paket from reintroducing the
reference.
Also the nuget package should be fixed

**Comment by konste** [comment]
I don't understand "and set all other Paket nodes to true"! Example?

And NuGet package was in fact fixed, but Microsoft in its infinite wisdom made the newer fixed package only for .Net 4.5.2, so we could not use it in the app targeting 4.5 proper. This made me went through the exercise of retargeting about 200 projects from 4.5 to 4.5.2. Currently it is finished, but it was not easy.

**Comment by forki** [comment]
<Paket>False</Paket>

sorry I meant "false"

**Comment by konste** [comment]
As far as I understand <Paket>True</Paket> is a marker to signal that this reference is managed by Paket. So I understand the case with no marker, or Paket = true. What Paket = False even means then?
Isn't it the same as no marker at all?

I still cannot grasp your recipe "remove the reference manually and set all other nodes to Paket=false" How exactly would it help?

**Comment by forki** [comment]
1) Manually removing the reference fixes your project.
2) setting one of the paket nodes to false tells paket to stop managing
this package.
3) when the package is fixed you can run "paket update --hard" to tell
paket to take control again

As far as I understand True is a marker to signal that this reference is
managed by Paket. So I understand the case with no marker, or Paket = true.
What Paket = False even means then?
Isn't it the same as no marker at all?

I still cannot grasp your recipe "remove the reference manually and set all
other nodes to Paket=false" How exactly would it help?

—
Reply to this email directly or view it on GitHub
<https://github.com/fsprojects/Paket/issues/1112#issuecomment-147420324>.

**Comment by konste** [comment]
Ah, --hard option was the part I was missing. Now I understand. Thank you!
