### ISSUE TITLE
Framework resolution strategy for Google.Apis.Oauth2.v2

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#1663]
### Description

Cannot use `Google.Apis.Oauth2.v2` with `Paket` for `Net45` project
Paket does not setup references properly in this case

### Expected behavior

![image](https://cloud.githubusercontent.com/assets/1197905/15045191/f4704a88-12e1-11e6-8850-d10e8a6e8164.png)

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="BouncyCastle" version="1.7.0" targetFramework="net45" />
  <package id="Google.Apis" version="1.11.1" targetFramework="net45" />
  <package id="Google.Apis.Auth" version="1.11.1" targetFramework="net45" />
  <package id="Google.Apis.Core" version="1.11.1" targetFramework="net45" />
  <package id="Google.Apis.Oauth2.v2" version="1.12.0.454" targetFramework="net45" />
  <package id="log4net" version="2.0.3" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net45" />
  <package id="Zlib.Portable.Signed" version="1.11.0" targetFramework="net45" />
</packages>
```

### Actual behavior

**paket.dependencies**
```
source https://nuget.org/api/v2

nuget Google.Apis.Oauth2.v2
```

**paket.lock**
```
NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    BouncyCastle (1.8.1)
    Google.Apis (1.10) - framework: portable-net40+sl5+win8+wp8+wpa81
      Google.Apis.Core (>= 1.10)
      log4net (>= 2.0.3) - framework: >= net40
      Zlib.Portable.Signed (>= 1.11)
    Google.Apis.Auth (1.11.1) - framework: portable-net45+win8+wp8+wpa81
      BouncyCastle (>= 1.7) - framework: >= net45
      Google.Apis.Core (>= 1.11.1)
    Google.Apis.Core (1.11.1) - framework: portable-net40+sl5+win8+wp8+wpa81, portable-net45+win8+wp8+wpa81
      Microsoft.Bcl (>= 1.1.10) - framework: net10, net11, net20, net30, net35, net40, net40-full
      Microsoft.Bcl.Async (>= 1.0.168) - framework: net10, net11, net20, net30, net35, net40, net40-full
      Microsoft.Bcl.Build (>= 1.0.21) - framework: net10, net11, net20, net30, net35, net40, net40-full
      Microsoft.Net.Http (>= 2.2.29) - framework: net10, net11, net20, net30, net35, net40, net40-full
      Newtonsoft.Json (>= 7.0.1)
    Google.Apis.Oauth2.v2 (1.12.0.454)
      Google.Apis (>= 1.11.1) - framework: portable-net45+win8+wp8+wpa81
      Google.Apis (1.10) - framework: portable-net40+sl5+win8+wp8+wpa81
      Google.Apis.Auth (>= 1.11.1) - framework: portable-net45+win8+wp8+wpa81
      Google.Apis.Auth (1.10) - framework: portable-net40+sl5+win8+wp8+wpa81
    log4net (2.0.5)
    Microsoft.Bcl (1.1.10)
      Microsoft.Bcl.Build (>= 1.0.14)
    Microsoft.Bcl.Async (1.0.168)
      Microsoft.Bcl (>= 1.1.8)
    Microsoft.Bcl.Build (1.0.21) - import_targets: false
    Microsoft.Net.Http (2.2.29)
      Microsoft.Bcl (>= 1.1.10)
      Microsoft.Bcl.Build (>= 1.0.14)
    Newtonsoft.Json (8.0.3) - framework: portable-net40+sl5+win8+wp8+wpa81, portable-net45+win8+wp8+wpa81
    Zlib.Portable.Signed (1.11) - framework: portable-net40+sl5+win8+wp8+wpa81

```

![image](https://cloud.githubusercontent.com/assets/1197905/15045242/41dc727e-12e2-11e6-819a-34a48400a4a3.png)

![image](https://cloud.githubusercontent.com/assets/1197905/15045295/71a7db2e-12e2-11e6-99e0-bc18f381773c.png)

### Known workarounds

Use NuGet =(

### Related information 

* `Paket 2.64.0.0`

**Comment by forki** [comment]
fixed in 2.64.2

**Comment by sergey-tihon** [comment]
Hmm.. Looks like it does not work for indirect dependencies
![image](https://cloud.githubusercontent.com/assets/1197905/15120498/9dd0a1b0-161e-11e6-81d5-e169b6674adb.png)
![image](https://cloud.githubusercontent.com/assets/1197905/15120545/e9a60d0a-161e-11e6-9456-fc6c02f21043.png)
Instead of 
![image](https://cloud.githubusercontent.com/assets/1197905/15045191/f4704a88-12e1-11e6-8850-d10e8a6e8164.png)

**Comment by forki** [comment]
can you try update -f ?

**Comment by sergey-tihon** [comment]
Better but still not all
![image](https://cloud.githubusercontent.com/assets/1197905/15121185/fff53470-1621-11e6-94d4-cd869713a833.png)
![image](https://cloud.githubusercontent.com/assets/1197905/15121189/07523812-1622-11e6-9168-7b1899915a7e.png)

**Comment by forki** [comment]
What is still missing? Will look into it tomorrow.

**Comment by sergey-tihon** [comment]
All yellow warn messages `Google.Apis`,  `log4net` & `Zlib`

**Comment by sergey-tihon** [comment]
Very interesting case here... Look at lock file
```
    Google.Apis.Oauth2.v2 (1.12.0.454)
      Google.Apis (>= 1.11.1) - framework: >= net45, portable-net45+win8+wp8+wpa81
      Google.Apis (1.10) - framework: net40, portable-net40+sl5+win8+wp8+wpa81
      Google.Apis.Auth (>= 1.11.1) - framework: >= net45, portable-net45+win8+wp8+wpa81
      Google.Apis.Auth (1.10) - framework: net40, portable-net40+sl5+win8+wp8+wpa81
```
`Google.Apis` has special version with `net45` support.

__Google.Apis (1.10)__:
![image](https://cloud.githubusercontent.com/assets/1197905/15138754/9ea92ebe-169a-11e6-89f7-2295fd53ec91.png)

__Google.Apis (1.11.1)__:
![image](https://cloud.githubusercontent.com/assets/1197905/15138763/b0dfdaec-169a-11e6-8b53-363565422166.png)

But `Paket` by design have to choose one version for solution, and here it choose min version `1.10`
```
    Google.Apis (1.10) - framework: net40, portable-net40+sl5+win8+wp8+wpa81
      Google.Apis.Core (>= 1.10)
      log4net (>= 2.0.3) - framework: >= net40
      Zlib.Portable.Signed (>= 1.11)
```
and this decisions does not work for `net45` projects.

**Comment by forki** [comment]
yes. we don't support such constellation.

**Comment by forki** [comment]
I will try to make it work for

    source https://nuget.org/api/v2
    framework: net45
    nuget Google.Apis.Oauth2.v2 1.12.0.454

**Comment by forki** [comment]
it's giving me

    FRAMEWORK: NET45
    NUGET
      remote: https://www.nuget.org/api/v2
      specs:
        BouncyCastle (1.8.1)
        Google.Apis (1.11.1)
          Google.Apis.Core (>= 1.11.1)
          log4net (>= 2.0.3)
          Zlib.Portable.Signed (>= 1.11)
        Google.Apis.Auth (1.11.1)
          BouncyCastle (>= 1.7)
          Google.Apis.Core (>= 1.11.1)
        Google.Apis.Core (1.11.1)
          Newtonsoft.Json (>= 7.0.1)
        Google.Apis.Oauth2.v2 (1.12.0.454)
          Google.Apis (>= 1.11.1)
          Google.Apis.Auth (>= 1.11.1)
        log4net (2.0.5)
        Newtonsoft.Json (8.0.3)
        Zlib.Portable.Signed (1.11)

that sounds ok

**Comment by sergey-tihon** [comment]
Thank you, I think that it is OK for now (same result on my machine)
Now I have to understand how Paket modified all my proj files again)
