### ISSUE TITLE
Paket exe can't handle paths that are longer than 260 characters.

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#949]
Between version 1.19.6 and 1.19.7 Paket became unable to handle paths longer than 260 characters.  any paket operation, whether via command line or VS integration, blows up with a PathTooLongException now in a solution we have that is a web app, and so has very long nested node_modules directories.

**Comment by baronfel** [comment]
Detailed stack trace:

``Paket failed with:
        The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
StackTrace:
     at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Microsoft.FSharp.Collections.ArrayModule.Collect[T,TResult](FSharpFunc`2 mapping, T[] array)
   at <StartupCode$Paket-Core>.$ProjectFile.search@55-2(String pattern, DirectoryInfo di)
   at Paket.ProjectFile.FindAllProjects(String folder)
   at Paket.InstallProcess.findAllReferencesFiles(String root)
   at Paket.UpdateProcess.SmartInstall(String dependenciesFileName, Boolean updateAll, FSharpOption`1 exclude, UpdaterOptions options)
   at <StartupCode$Paket-Core>.$PublicAPI.Install@156.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@280-10.Invoke(ArgParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@71-1.Invoke(Command command, String[] args)
   at Paket.Program.main()``

**Comment by forki** [comment]
also reported in https://twitter.com/chrismckee/status/626756973283950592

**Comment by baronfel** [comment]
we could try adding support for the ``\\?\<FILEPATH>`` syntax, which opts-in to long path support in win32: http://blogs.msdn.com/b/bclteam/archive/2007/02/13/long-paths-in-net-part-1-of-3-kim-hamilton.aspx

**Comment by ChrisMcKee** [comment]
+1 When it does find all refs is it scanning all the folders? Just wondering as I have a 'master' folder in my repo which isnt part of the solution, in there is some frontend crap for gulp that handles live reload etc; It's only the npm folder in here that exceeds the win limit (mostly caused by lodash dependencies). But I wouldn't expect Paket to be looking at anything thats not in SLN/CSProj

**Comment by forki** [comment]
could you please check if 1.22.0-alpha005 fixes it?
you can use `paket.bootstrapper.exe prerelease` to get that version

**Comment by baronfel** [comment]
it does fix the issue for me. Thanks for the quick turnaround, @forki.

**Comment by forki** [comment]
ok cool. will release a proper version.

**Comment by forki** [comment]
done http://fsprojects.github.io/Paket/release-notes.html

**Comment by ChrisMcKee** [comment]
Yup that wins :) Thanks

**Comment by baronfel** [comment]
can you also push an update of Paket.VisualStudio to contain this fix?  It's a bit of heartburn for us without it.

**Comment by forki** [comment]
Already done

**Comment by bhugot** [comment]
Hi,

I still get the issue especially with the new core libs which have really long name like
runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl

**Comment by AndyBehr** [comment]
The PathTooLong Exception is still happening
` Paket failed with:
   -> PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

What broke it again?
